name: Push components to Espressif Component Service

on:
  push:
    branches:
      - release/v2.0

jobs:
  upload_components:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          submodules: 'recursive'
      - name: Upload components to component service
        uses: espressif/upload-components-ci-action@v1
        with:
          name: "Physac"
          namespace: "yanke01"
          api_token: ${{secrets.IDF_COMPONENT_API_TOKEN}}